#!/bin/sh

set -o errexit

argcount=1
usage="named_pipe_path_to_create"
test "$#" -ge "${argcount}" || { echo "$0 ${usage}" > /dev/stderr && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
set -o nounset

pipe="${1}"
shift

trap 'unlink -- "${pipe}"' \
    INT HUP ALRM PIPE PROF USR1 USR2 VTALRM STKFLT QUIT ABRT TERM EXIT

mkfifo "${pipe}"
echo "${pipe}" > /dev/stderr
cat - >> "${pipe}"
